# Generated by Django 4.0 on 2021-12-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_contact_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
